module Databases (isInWordlist, isPrefix, malenames, femalenames, wordlist, allPrefixes, thesaurus, synonyms) where 

import Debug.Trace
import Data.Text
import qualified Data.Set as Set
import qualified Data.Text    as Text
import qualified Data.Text.IO as Text
import qualified Data.Map as Map 
import Data.Array.IArray
import Data.Binary
import Data.ByteString.Lazy as BS

import System.IO.Unsafe

import Types
import ManualData

-- HEADLINE FUNCTIONS 


thesaurusLookup s = case (lookfor s) of 
  Nothing -> []
  Just s -> Prelude.map (\n -> keys!n) s

lookfor ::  String -> Maybe [Int]
lookfor s = Map.lookup s thesaurus

-- WORDLISTS

read_malenames = do
    ls <- fmap Text.lines (Text.readFile "data/malenames")
    (return . Set.fromList . string_read . toString . toLower . Prelude.head) ls
    
temp_malenames = unsafePerformIO $ do read_malenames
output_malenames = encodeFile "malenames.bin" temp_malenames

read_bytes_malenames :: IO (Set.Set String)
read_bytes_malenames = do
    return . decode =<< BS.readFile "malenames.bin"
    
malenames = trace "Male names..." (unsafePerformIO $ do read_bytes_malenames)

read_femalenames = do
    ls <- fmap Text.lines (Text.readFile "data/femalenames")
    (return . Set.fromList . string_read . toString . toLower . Prelude.head) ls
    
temp_femalenames = unsafePerformIO $ do read_femalenames
output_femalenames = encodeFile "femalenames.bin" temp_femalenames

read_bytes_femalenames :: IO (Set.Set String)
read_bytes_femalenames = do
    return . decode =<< BS.readFile "femalenames.bin"
    
femalenames = trace "Female names" (unsafePerformIO $ do read_bytes_femalenames)

read_wordlist = do
    ls <- fmap Text.lines (Text.readFile "data/straight-wordlist")
    (return . Set.fromList . string_read . toString . Prelude.head) ls
    
temp_wordlist = unsafePerformIO $ do read_wordlist
output_wordlist = encodeFile "wordlist.bin" temp_wordlist

read_bytes_wordlist :: IO (Set.Set String)
read_bytes_wordlist = do
    return . decode =<< BS.readFile "wordlist.bin"
    
wordlist = trace "Word list..." (unsafePerformIO $ do read_bytes_wordlist)

-- THESAURUS

read_thesaurus = do
    ls <- fmap Text.lines (Text.readFile "data/thesaurus-list")
    (return . Map.fromList . map_read . toString . Prelude.head) ls
     
temp_thesaurus = unsafePerformIO $ do read_thesaurus
output_thesaurus = encodeFile "thesaurus.bin" temp_thesaurus

read_bytes_thesaurus :: IO (Map.Map String [Int])
read_bytes_thesaurus = do
    return . decode =<< BS.readFile "thesaurus.bin"

thesaurus :: Map.Map String [Int]    
thesaurus = trace "Thesaurus..." (unsafePerformIO $ do read_bytes_thesaurus)


-- KEYS

read_keys = do
    ls <- fmap Text.lines (Text.readFile "data/thesaurus-list-keys")
    (return . makeArray . string_read . toString . Prelude.head) ls
     
temp_keys = unsafePerformIO $ do read_keys
output_keys = encodeFile "keys.bin" temp_keys

read_bytes_keys :: IO (Array Int String)
read_bytes_keys = do
    return . decode =<< BS.readFile "keys.bin"
    
keys = trace "Keys..." (unsafePerformIO $ do read_bytes_keys)


-- Stuff...

makeArray :: [String] -> Array Int String
makeArray ss = listArray (0, (Prelude.length ss) - 1) ss

toString = Text.unpack

map_read :: String -> [(String, [Int])]
map_read = read

string_read :: String -> [String]
string_read = read

isInWordlist x = Set.member x wordlist_extended'

wordlist_extended' = Set.union (Set.fromList (Map.keys thesaurus)) wordlist_extended 
wordlist_extended = Set.union (Set.fromList manualWords) wordlist

------ PREFIXES ------

isPrefix s 
  = Set.member s allPrefixes

allPrefixes = trace "Prefixes..." (Set.fromList (Prelude.concatMap prefixes (Set.elems wordlist_extended')))

prefixes []
  = []
prefixes (c : cs)
  = [c] : Prelude.map (c :) (prefixes cs)

------ SYNONYMS ------

isSynonym w w' = Prelude.elem w (synonyms w')

synonyms :: String -> [String]
synonyms ('t' : 'o' : ' ' : s) 
  = synonyms s
synonyms s 
  = s : (Prelude.filter (not . Prelude.null) $ thesaurusLookup s ++
    maybe [] id (Map.lookup s abbreviations) ++ 
    manualSynonym s ++ 
    manualAbbreviation s ++ 
    lookUp s nameSynonyms)

lookUp x t
  = maybe [] id (Prelude.lookup x t)

associate syns names
  = Prelude.map (\s -> (s,names)) syns

nameSynonyms 
  = associate malesynonyms (Set.elems malenames) ++
    associate femalesynonyms (Set.elems femalenames)

malesynonyms
  = ["man", "him", "his name", "name", "boy", "he"]

femalesynonyms
  = ["woman", "her", "her name", "name", "girl", "she"]


------- ABBREVIATONS --------

abbreviations
  = Map.fromList [("12.5 cents", ["dime"]),
     ("45 minutes", ["our","hou"]),
     ("666", ["mb"]),
     ("a", ["i"]),
     ("a follower", ["b"]),
     ("able seaman", ["salt","tar","sailor","ab"]),
     ("able to", ["can"]),
     ("about", ["ca","on","re","c"]),
     ("about turn", ["u"]),
     ("abstaining", ["tt"]),
     ("academic", ["ma","prof"]),
     ("academician", ["ra","a","ara","pra"]),
     ("academy", ["rada","ra"]),
     ("acceptable", ["u","ok"]),
     ("accepted", ["a"]),
     ("account", ["ac","acc"]),
     ("accountant", ["ca","aca","ac"]),
     ("ace", ["a","ai"]),
     ("acre", ["a"]),
     ("across", ["x"]),
     ("act", ["do"]),
     ("acting", ["on"]),
     ("active", ["a"]),
     ("actor", ["tree","ham"]),
     ("actuary", ["aia","fia"]),
     ("admitting", ["am","iam","im"]),
     ("adult", ["a"]),
     ("advanced", ["lent","a"]),
     ("advertisement", ["ad"]),
     ("aeroplane", ["mig"]),
     ("after date", ["ad"]),
     ("after the style of", ["ala"]),
     ("afternoon", ["a","iam","pm"]),
     ("again", ["bis","re"]),
     ("against", ["con","v"]),
     ("age", ["eon"]),
     ("aged", ["aet","ae"]),
     ("agent", ["rep","spy","v","g"]),
     ("agreement", ["ay","ja","aye","yea","da","oui","si"]),
     ("airborne soldier", ["para"]),
     ("aircraftsman", ["ac","lac"]),
     ("airline", ["ba","bac","bea"]),
     ("airman", ["po"]),
     ("Alabama", ["al","ala"]),
     ("Alan", ["al"]),
     ("Alaska", ["alas"]),
     ("Albania", ["al"]),
     ("Albert", ["al"]),
     ("alcoholic state", ["dt"]),
     ("aleph", ["a"]),
     ("alien", ["et"]),
     ("all right", ["ok"]),
     ("allow", ["let"]),
     ("allowed", ["let"]),
     ("alloy", ["y"]),
     ("alpha", ["a"]),
     ("alternating current", ["ac"]),
     ("alternative", ["or"]),
     ("alternatively", ["or"]),
     ("alto", ["a"]),
     ("aluminium", ["al"]),
     ("always", ["ay","ere","aye","eer"]),
     ("amateur", ["a"]),
     ("amateur's department", ["diy"]),
     ("ambassador", ["he"]),
     ("America", ["us","usa","am"]),
     ("American", ["am","amer","us"]),
     ("American detective", ["fed","g-man"]),
     ("American lawyer", ["da"]),
     ("American man", ["bo"]),
     ("American policeman", ["bull"]),
     ("American railway", ["el"]),
     ("American soldier", ["joe","gi"]),
     ("ampere", ["a"]),
     ("an", ["a","i"]),
     ("anaesthetic", ["number"]),
     ("anarchist", ["red"]),
     ("ancient city", ["ur","troy"]),
     ("ancient times", ["bc"]),
     ("and", ["et"]),
     ("ane", ["a","i"]),
     ("anger", ["ire"]),
     ("angle", ["l"]),
     ("Anglo-Saxon", ["as"]),
     ("angstrom", ["a"]),
     ("annual meeting", ["agm"]),
     ("answer", ["a","ans"]),
     ("ante", ["a"]),
     ("appeal", ["sos"]),
     ("appearance", ["air"]),
     ("application", ["use"]),
     ("apprentice", ["l"]),
     ("approval", ["ok"]),
     ("approx", ["ca","some","c"]),
     ("approximately", ["some","c","ca"]),
     ("arab", ["ar"]),
     ("archbishop", ["cantuar","laud","ebor"]),
     ("archdeacon", ["ven"]),
     ("archer", ["tell"]),
     ("are", ["r","a"]),
     ("argy", ["rg"]),
     ("argy-bargy", ["rg"]),
     ("arithmetic", ["r"]),
     ("army", ["ta"]),
     ("army regulation", ["ar"]),
     ("around", ["o","c"]),
     ("arrival", ["arr","ar"]),
     ("arrive", ["arr","ar"]),
     ("ars", ["rr"]),
     ("art nouveau", ["rat","tar"]),
     ("article", ["the"]),
     ("articles", ["a"]),
     ("articles - English", ["an","the"]),
     ("articles - French", ["la","les","le"]),
     ("articles - German", ["der","die","das"]),
     ("articles - Italian", ["il","la"]),
     ("articles - Spanish", ["la","el","los"]),
     ("artillery", ["ra"]),
     ("artist", ["ra","lely","ara","pra","etty"]),
     ("arty", ["rt"]),
     ("as", ["s","qua"]),
     ("as above", ["us"]),
     ("Asian", ["e"]),
     ("associate", ["a"]),
     ("at home", ["in"]),
     ("at one on", ["ation"]),
     ("at university", ["up"]),
     ("atomic", ["a"]),
     ("attempt", ["try"]),
     ("aught", ["o"]),
     ("Australia", ["aus"]),
     ("Austria", ["a"]),
     ("author", ["pen"]),
     ("authorisation", ["ok"]),
     ("autobiography", ["cv"]),
     ("average", ["ave","aver"]),
     ("Avogadro's number", ["n"]),
     ("award", ["om","obe","ch"]),
     ("away", ["out"]),
     ("ay", ["a","i"]),
     ("aye", ["i","a"]),
     ("ayes", ["is","as"]),
     ("ays", ["is","as"]),
     ("Azed", ["az"]),
     ("Bach", ["b"]),
     ("Bach's works", ["s"]),
     ("bachelor", ["b","ba"]),
     ("Bachelor of Arts", ["ba"]),
     ("bad actor", ["ham"]),
     ("bad French", ["mal"]),
     ("badly", ["ill"]),
     ("bald patch", ["o"]),
     ("ball", ["o"]),
     ("bandage", ["t"]),
     ("bank rate", ["br"]),
     ("banker", ["river"]),
     ("bar", ["t","z"]),
     ("barbarian", ["hun"]),
     ("bargain", ["go"]),
     ("barium", ["ba"]),
     ("bark", ["woof","tan"]),
     ("baron", ["b"]),
     ("barrel", ["b"]),
     ("barrels", ["b"]),
     ("barrier", ["dam"]),
     ("bass", ["b"]),
     ("batting", ["in"]),
     ("beady", ["bd"]),
     ("beard", ["awn"]),
     ("bears", ["has"]),
     ("beat", ["lam","tan"]),
     ("bed", ["cot"]),
     ("bedbug", ["b"]),
     ("bee", ["b"]),
     ("beer", ["ale"]),
     ("bees", ["bs","bb"]),
     ("Beethoven", ["b"]),
     ("before", ["or","a","an","ere"]),
     ("before Christ", ["ac","bc"]),
     ("before food", ["ac"]),
     ("before the day", ["ad"]),
     ("beginning", ["alpha"]),
     ("being broadcast", ["on"]),
     ("bel", ["b"]),
     ("Belgium", ["b"]),
     ("bend", ["u","z","s"]),
     ("bender", ["knee"]),
     ("beta", ["b"]),
     ("beth", ["b"]),
     ("beware", ["kv"]),
     ("bible", ["rv","av"]),
     ("big", ["os"]),
     ("big banger", ["tnt"]),
     ("big bell", ["tom"]),
     ("big guns", ["ra"]),
     ("big noise", ["vip"]),
     ("bikini", ["atoll"]),
     ("bill", ["ac","acc"]),
     ("bird", ["prison","tit"]),
     ("bishop", ["bp","rr","b","odo"]),
     ("bit", ["ort"]),
     ("black", ["b"]),
     ("blob", ["o"]),
     ("blockbuster", ["sculptor"]),
     ("blood group", ["o","b","a"]),
     ("bloody", ["red","b"]),
     ("bloomer", ["flower"]),
     ("blue", ["sad"]),
     ("bluetit", ["nun"]),
     ("blunder", ["err"]),
     ("boasting", ["am","iam","im"]),
     ("boat", ["q","e","u"]),
     ("bob", ["s"]),
     ("body", ["x"]),
     ("bomb", ["v","a","egg","h"]),
     ("Bond's boss", ["m"]),
     ("bone", ["os","t"]),
     ("book", ["b","nt","ot","lib","tome","vol","bk"]),
     ("bookmaker", ["amos","job"]),
     ("books", ["bb","ot","nt"]),
     ("born", ["n","ne","nat","b","nee"]),
     ("boron", ["b"]),
     ("bound", ["bd"]),
     ("bowled", ["b"]),
     ("bowler", ["drake"]),
     ("boy", ["b"]),
     ("Brahms", ["b"]),
     ("brakes", ["abs"]),
     ("branch", ["br"]),
     ("Brazilian", ["para"]),
     ("breadth", ["b"]),
     ("bridge", ["br"]),
     ("bridge opponents", ["nw","sw","ne","se"]),
     ("bridge partners", ["ns","ew"]),
     ("bridge players", ["n","e","s","w"]),
     ("brief reply", ["ans"]),
     ("brig", ["br"]),
     ("Britain", ["b","br"]),
     ("British", ["b","br"]),
     ("British company", ["bl"]),
     ("British Museum", ["bm"]),
     ("British Rail", ["br"]),
     ("brother", ["bro","br"]),
     ("brown", ["br","tan"]),
     ("bull", ["ox"]),
     ("business", ["co","biz","firm","ado"]),
     ("busy", ["tec"]),
     ("Butler", ["rab"]),
     ("butter", ["ram"]),
     ("buzzer", ["bee"]),
     ("by", ["per"]),
     ("cagey", ["kg"]),
     ("Cakesville", ["eccles"]),
     ("calcium", ["ca"]),
     ("California", ["cal"]),
     ("can", ["may","tin","able"]),
     ("cape", ["c"]),
     ("Capek's play", ["rur"]),
     ("capital", ["ai"]),
     ("capital authority", ["glc"]),
     ("Capone", ["al"]),
     ("captain", ["cid","old man"]),
     ("capture", ["net"]),
     ("caput", ["c"]),
     ("car", ["rr","mini"]),
     ("car test", ["mot"]),
     ("carat", ["car","ct"]),
     ("carbon", ["c"]),
     ("carbon monoxide", ["co"]),
     ("card", ["ace"]),
     ("care of", ["co"]),
     ("cart", ["t"]),
     ("cases", ["ca"]),
     ("cash", ["tin"]),
     ("castle", ["oo","r"]),
     ("cat", ["tom","mog","rex"]),
     ("cattle", ["kine","neat"]),
     ("caught", ["ct","c"]),
     ("cave", ["kv"]),
     ("cavity", ["o"]),
     ("cavy", ["kv"]),
     ("cayenne", ["kn"]),
     ("cedi", ["c"]),
     ("cedilla", ["z"]),
     ("Celsius", ["c"]),
     ("Celt", ["q","p"]),
     ("censor", ["edit","cato"]),
     ("cent", ["red","ct","c"]),
     ("centi-", ["c"]),
     ("centigrade", ["c"]),
     ("centime", ["ct","c"]),
     ("central heating", ["ch"]),
     ("century", ["c"]),
     ("certain", ["sure"]),
     ("champion", ["ace","ch"]),
     ("Channel Islands", ["ci"]),
     ("chapter", ["ch","cap","c"]),
     ("Charles", ["c"]),
     ("che", ["i"]),
     ("cheat", ["do"]),
     ("cheers", ["ta"]),
     ("chemical", ["nitre"]),
     ("chemist", ["mps"]),
     ("cherished", ["pet"]),
     ("chess grandmaster", ["tal"]),
     ("chess piece", ["pawn"]),
     ("chewed", ["bit"]),
     ("chi", ["x"]),
     ("chief", ["ch","cid"]),
     ("chief executive", ["dg"]),
     ("child", ["ch","brat"]),
     ("childless", ["sp"]),
     ("children", ["seed"]),
     ("chimney", ["lum"]),
     ("China", ["ch","ming"]),
     ("China area", ["fare"]),
     ("Chinese dynasty", ["han","ming"]),
     ("chlorine", ["cl"]),
     ("Christ", ["x"]),
     ("Christian era", ["ad"]),
     ("Christmas period", ["dec"]),
     ("chromosome", ["y","x"]),
     ("church", ["ce","rc","ch"]),
     ("Church of England", ["ce"]),
     ("cipher", ["o"]),
     ("circa", ["c"]),
     ("circle", ["ring","disc","o"]),
     ("circuit", ["o"]),
     ("circular letter", ["o"]),
     ("citation", ["cit"]),
     ("city", ["ec","ely"]),
     ("Civil Service", ["cs"]),
     ("class", ["cl"]),
     ("classical musician", ["orpheus"]),
     ("clause", ["cl"]),
     ("clear", ["rid"]),
     ("clef", ["f","g"]),
     ("cleric", ["bd","dd"]),
     ("close", ["nie"]),
     ("cloth", ["t","rep"]),
     ("cloudy", ["c"]),
     ("club", ["c"]),
     ("cobalt", ["co"]),
     ("Cockney girl", ["er"]),
     ("cocktail", ["egg"]),
     ("cold", ["c"]),
     ("collection", ["ans"]),
     ("college", ["eton","c","poly"]),
     ("Colombia", ["co"]),
     ("commander", ["oc","cinc","co","com"]),
     ("commanding officer", ["co"]),
     ("commotion", ["todo"]),
     ("communist", ["red"]),
     ("companion", ["ch"]),
     ("Companion of Honour", ["ch"]),
     ("company", ["two","co","firm"]),
     ("completely", ["all"]),
     ("complex number", ["c"]),
     ("concerning", ["re"]),
     ("condition", ["if"]),
     ("confusion", ["pi"]),
     ("Connecticut", ["ct"]),
     ("Conservative", ["tory","c","blue","con","u"]),
     ("conspirator", ["cade","oates"]),
     ("constant", ["k"]),
     ("contemporary", ["ad"]),
     ("continent", ["eur","asia"]),
     ("contralto", ["c"]),
     ("contrivance", ["art"]),
     ("cook", ["do"]),
     ("copper", ["d","p","cu","pc"]),
     ("copy", ["ape"]),
     ("copyright", ["c"]),
     ("corn", ["rip"]),
     ("corner", ["l"]),
     ("Cornwall", ["sw"]),
     ("corporation", ["tum"]),
     ("correct", ["ok"]),
     ("corruption", ["rot"]),
     ("coulomb", ["c"]),
     ("counter", ["gm","geiger"]),
     ("county", ["co","down","som","avon"]),
     ("county council", ["cc"]),
     ("court", ["ct"]),
     ("cove", ["man"]),
     ("cow", ["lower"]),
     ("craft", ["art"]),
     ("credit", ["cr"]),
     ("credit notes", ["ious"]),
     ("cross", ["t","x","zo","tau"]),
     ("crossed", ["t"]),
     ("crown", ["cr"]),
     ("cry of delight", ["ole"]),
     ("cry of triumph", ["io"]),
     ("Cuba", ["c"]),
     ("cue", ["q"]),
     ("cunning", ["art"]),
     ("cup holder", ["hebe"]),
     ("current", ["ac","dc"]),
     ("curse", ["ban"]),
     ("curve", ["arc"]),
     ("custom", ["use"]),
     ("cutie", ["qt"]),
     ("Czechoslovakia", ["cs"]),
     ("Dad's army", ["hg"]),
     ("dagger", ["da"]),
     ("daily", ["times","char"]),
     ("daisy", ["cow"]),
     ("damn", ["d"]),
     ("dance", ["pas"]),
     ("dark blue", ["oxonian"]),
     ("date", ["d"]),
     ("daughter", ["d"]),
     ("dawn", ["nus"]),
     ("day", ["v","d"]),
     ("days", ["dd"]),
     ("dead", ["d","obit"]),
     ("dead reckoning", ["dr"]),
     ("dear", ["chere","cher"]),
     ("debtor", ["dr"]),
     ("decay", ["rot"]),
     ("decentralise", ["core"]),
     ("deci", ["d"]),
     ("decimally", ["intens"]),
     ("decisive blow", ["ko"]),
     ("decree", ["act"]),
     ("Dee", ["d"]),
     ("deep", ["main","sea"]),
     ("degree", ["ma","deg","ba","d"]),
     ("delete", ["d"]),
     ("delta", ["d"]),
     ("Democrat", ["d"]),
     ("Denmark", ["dk"]),
     ("density", ["d"]),
     ("desert", ["rat"]),
     ("desert fighter", ["rat"]),
     ("deserted", ["d"]),
     ("deserter", ["rat"]),
     ("designer", ["dior"]),
     ("dessert", ["fool"]),
     ("detective", ["det","tec"]),
     ("detectives", ["cid","yard"]),
     ("deuterium", ["d"]),
     ("Deutsch", ["d"]),
     ("Devon", ["sw"]),
     ("dial", ["o"]),
     ("diameter", ["d"]),
     ("diamond", ["ice","rock","d"]),
     ("diamonds", ["ice"]),
     ("died", ["d","obit"]),
     ("differential operator", ["d"]),
     ("difficulty", ["ado","er"]),
     ("dime", ["ioc"]),
     ("diplomat", ["cd"]),
     ("Dirac's constant", ["h"]),
     ("direction", ["e","s","w","n"]),
     ("director", ["d"]),
     ("director general", ["dg"]),
     ("directors", ["board"]),
     ("disadvantage", ["ward"]),
     ("disc", ["o"]),
     ("display", ["air"]),
     ("District Attorney", ["da"]),
     ("ditch", ["haha"]),
     ("ditto", ["do"]),
     ("divine", ["dd"]),
     ("doctor", ["bm","mb","who","md","mo","dd","dr","gp"]),
     ("doctor of divinity", ["dd"]),
     ("doctrine", ["ism"]),
     ("dog", ["cur","tail","mutt"]),
     ("doll", ["qp"]),
     ("dollar", ["s"]),
     ("don't change it", ["stet"]),
     ("donkey", ["ned","ass"]),
     ("double", ["di","bi","ka"]),
     ("double act", ["dodo"]),
     ("doubt", ["um"]),
     ("doughboy", ["gi"]),
     ("drag", ["d"]),
     ("dram", ["dr"]),
     ("draw", ["x"]),
     ("drawback", ["ward"]),
     ("drawer", ["dr"]),
     ("dressmaker", ["satin","silk"]),
     ("drinking", ["on"]),
     ("drowned valley", ["ria"]),
     ("drunk", ["lit"]),
     ("dry", ["sec","tt"]),
     ("duck", ["o"]),
     ("duck's eggs", ["oo"]),
     ("duke", ["fist","d"]),
     ("Durham area", ["ne"]),
     ("Dutch uncle", ["oom"]),
     ("each", ["ea"]),
     ("early morning", ["iam"]),
     ("earth", ["ge","e"]),
     ("ease", ["es","ee"]),
     ("east", ["e","ost"]),
     ("East Africa", ["ea"]),
     ("eastern", ["e"]),
     ("ecclesiastical title", ["ven"]),
     ("economist", ["mill","smith"]),
     ("ecstatic", ["sent"]),
     ("Ecuador", ["ec"]),
     ("editor", ["ed"]),
     ("educated man", ["ma"]),
     ("educational establishment", ["u","eton"]),
     ("educational journal", ["test"]),
     ("Edward", ["e","ed","ted"]),
     ("eec", ["twelve"]),
     ("effect", ["a"]),
     ("egg", ["o"]),
     ("Egypt", ["et"]),
     ("eight", ["e"]),
     ("eight thousand", ["e"]),
     ("eighty", ["r"]),
     ("eighty thousand", ["r"]),
     ("el", ["l"]),
     ("elected", ["in"]),
     ("electoral system", ["pr"]),
     ("electrical capacity", ["c"]),
     ("electrical charge", ["q"]),
     ("electrical current", ["i"]),
     ("electrical flux", ["d"]),
     ("elevated railway", ["l"]),
     ("eleven", ["xi","o","ii"]),
     ("eleven thousand", ["o"]),
     ("Elizabeth", ["e"]),
     ("ell", ["l"]),
     ("ells", ["ll","ls"]),
     ("els", ["ll","ls"]),
     ("em", ["m"]),
     ("employ", ["use"]),
     ("employment", ["use"]),
     ("empty", ["o"]),
     ("empty container", ["tion"]),
     ("ems", ["mm","ms"]),
     ("en", ["n"]),
     ("enclosure", ["pen"]),
     ("encourage", ["egg"]),
     ("energy", ["go","e"]),
     ("engineer", ["ce","re"]),
     ("engineers", ["re","reme","ce"]),
     ("England", ["eng","e"]),
     ("English", ["eng","e"]),
     ("ens", ["ns","nn"]),
     ("envy", ["nv"]),
     ("epistle", ["ep"]),
     ("epsilon", ["e"]),
     ("era", ["ad"]),
     ("ergo", ["so"]),
     ("err", ["sin"]),
     ("es", ["s"]),
     ("ess", ["s"]),
     ("essay", ["sa","try"]),
     ("Essen", ["sn"]),
     ("Essex", ["sx"]),
     ("estimated time of arrival", ["eta"]),
     ("eta", ["e"]),
     ("ever", ["er","eer","ay","aye"]),
     ("everybody", ["all"]),
     ("everything", ["all"]),
     ("evil", ["sin"]),
     ("ewe", ["u"]),
     ("ewes", ["us","uu"]),
     ("ex", ["x"]),
     ("examination", ["test","a","o","oral"]),
     ("excel", ["xl"]),
     ("excellency", ["he"]),
     ("excited", ["up"]),
     ("Exe", ["x"]),
     ("exist", ["be"]),
     ("existing state", ["asis"]),
     ("exists", ["iss"]),
     ("exotic", ["et"]),
     ("expert", ["ace","dab","able","pro"]),
     ("explosive", ["tnt","he"]),
     ("extraterrestrial", ["et"]),
     ("extremity", ["toe"]),
     ("eye", ["i"]),
     ("eyes", ["ii","is"]),
     ("eyesore", ["stye"]),
     ("fabric", ["net"]),
     ("fabulous bird", ["roc"]),
     ("fabulous hare", ["loser"]),
     ("fabulous tortoise", ["winner"]),
     ("Fahrenheit", ["f"]),
     ("fairly quiet", ["mp"]),
     ("fairy queen", ["mab"]),
     ("farad", ["f"]),
     ("farewell", ["vale"]),
     ("farthing", ["q","f"]),
     ("fashion", ["rage","ton"]),
     ("fashionable", ["in"]),
     ("fashionable people", ["ton"]),
     ("fast car", ["gt","rod"]),
     ("father", ["pa","dad","pop","time","fr"]),
     ("fathom", ["f"]),
     ("favoured", ["in"]),
     ("favourite", ["pet"]),
     ("feet", ["ft"]),
     ("fellow", ["f","man","gent","don"]),
     ("female", ["her","f","hen","she"]),
     ("female support", ["bra"]),
     ("female supporter", ["bra"]),
     ("feminine", ["f"]),
     ("fertiliser", ["nitre"]),
     ("field", ["ley","lea"]),
     ("fifty", ["a","l"]),
     ("fifty one", ["li"]),
     ("fifty pounds", ["ll"]),
     ("fifty thousand", ["l"]),
     ("fifty-fifty", ["ll"]),
     ("fighter", ["man","gi"]),
     ("fighters", ["uff"]),
     ("filly", ["f"]),
     ("film", ["et","u","a","x"]),
     ("filthy place", ["sty"]),
     ("final letter", ["omega","z"]),
     ("final message", ["obit","rip"]),
     ("final word", ["amen","omega"]),
     ("fine", ["scot","ok","f"]),
     ("firm", ["fast","co"]),
     ("first", ["ist"]),
     ("first character", ["a","adam","alpha"]),
     ("first class", ["ai","a"]),
     ("first item in sale", ["loti"]),
     ("first lady", ["eve"]),
     ("first letter", ["a","alpha"]),
     ("first mate", ["eve"]),
     ("first murderer", ["cain"]),
     ("first person", ["me","adam","i"]),
     ("first victim", ["abel"]),
     ("fish", ["ide","id","eel","gar","cod","ling"]),
     ("five", ["v","e"]),
     ("five hundred", ["a","q","d"]),
     ("five hundred and one", ["di"]),
     ("five hundred thousand", ["q"]),
     ("five thousand", ["a","e"]),
     ("fleet", ["rn"]),
     ("fliers", ["raf"]),
     ("Florida", ["fla"]),
     ("flourished", ["fl"]),
     ("flower", ["river","lis","rose"]),
     ("flowers", ["lei"]),
     ("fluorine", ["f"]),
     ("fly larva", ["bot"]),
     ("fly-by-night", ["bat","moth"]),
     ("folio", ["fo","f","fol"]),
     ("folios", ["ff"]),
     ("following", ["f"]),
     ("followings", ["ff"]),
     ("fool", ["ass"]),
     ("foot", ["f","ft"]),
     ("football", ["fa","ru"]),
     ("footnote", ["ps"]),
     ("for", ["pro"]),
     ("for all to see", ["u"]),
     ("for each", ["per"]),
     ("for example", ["eg","vg"]),
     ("for instance", ["eg"]),
     ("force", ["f","vis"]),
     ("forced", ["fz"]),
     ("Foreign Office", ["fo"]),
     ("former", ["ex"]),
     ("former squadron", ["red"]),
     ("forte", ["f"]),
     ("fortissimo", ["ff"]),
     ("forty", ["f"]),
     ("four", ["d","iv"]),
     ("four feet", ["ell"]),
     ("four hundred", ["p","g"]),
     ("four hundred thousand", ["p"]),
     ("four thousand", ["d"]),
     ("fourth man", ["seth"]),
     ("fox", ["tod"]),
     ("fragment", ["fr","ort"]),
     ("franc", ["fr"]),
     ("France", ["f"]),
     ("Franco-German agreement", ["ouija"]),
     ("free", ["rid"]),
     ("free of charge", ["foc"]),
     ("free on board", ["fob"]),
     ("free on rail", ["for"]),
     ("French", ["fr"]),
     ("French art", ["es"]),
     ("French king", ["sm","roi"]),
     ("French man", ["m","rene"]),
     ("French men", ["mm"]),
     ("French queen", ["reine","sm"]),
     ("French wine", ["vin"]),
     ("frequency", ["f"]),
     ("frequently", ["fr"]),
     ("friar", ["tuck"]),
     ("Friday", ["f","man"]),
     ("from", ["ex","de"]),
     ("from the", ["dela","du"]),
     ("full moon", ["o"]),
     ("fuss", ["ado"]),
     ("Gaelic", ["gael","erse"]),
     ("gallery", ["tate"]),
     ("game", ["nim"]),
     ("gamma", ["g"]),
     ("gamut", ["g"]),
     ("gangster", ["al"]),
     ("garden", ["eden","plot"]),
     ("gas", ["he","ne","f","cl","n","h","co","o"]),
     ("Gauss", ["g"]),
     ("gee", ["g"]),
     ("Gee-gee", ["gg"]),
     ("general", ["grant","gen","goc","lee"]),
     ("general service", ["gs"]),
     ("general staff", ["gs"]),
     ("generation", ["era"]),
     ("Genesis", ["gen"]),
     ("genius", ["id","ka"]),
     ("George", ["gr","g"]),
     ("Georgia", ["ga"]),
     ("German", ["hun"]),
     ("German soldier", ["ss"]),
     ("Germany", ["d","g"]),
     ("gift", ["gab"]),
     ("gin cocktail", ["ign","ing"]),
     ("girl", ["gal","g"]),
     ("globe", ["o"]),
     ("god", ["ra","pan","lar"]),
     ("God's", ["s"]),
     ("goddess", ["athena","isis","ate","hebe"]),
     ("gold", ["bull","or","au"]),
     ("good", ["ai","pi","a"]),
     ("good book", ["ot","nt"]),
     ("good man", ["dean","st"]),
     ("goodbye", ["tata","vale"]),
     ("Gort's men", ["bef"]),
     ("Gotham", ["ny"]),
     ("government issue", ["gi"]),
     ("governor", ["he"]),
     ("gracious me", ["my"]),
     ("gradually", ["eric"]),
     ("graduate", ["ba","ma"]),
     ("grain", ["gr"]),
     ("gram", ["g"]),
     ("grammar", ["gr"]),
     ("gramme", ["g","gr"]),
     ("grand", ["g"]),
     ("graphite", ["kish"]),
     ("gravity", ["g"]),
     ("Great Britain", ["gb"]),
     ("Greece", ["gr"]),
     ("Greek", ["gr"]),
     ("Greek character", ["nu","pi","mu"]),
     ("Greek letter", ["nu","alpha","lambda","omega","pi","mu","beta","chi","phi","eta","iota"]),
     ("greeting", ["ave","hi"]),
     ("group", ["set"]),
     ("group of workers", ["bee"]),
     ("grouse", ["gr"]),
     ("guerrilla", ["che"]),
     ("guinea", ["gu","g"]),
     ("gulf", ["o","g"]),
     ("gun", ["sten","arm","lewis","bren","gat","maxim"]),
     ("gunmen", ["grs","ra"]),
     ("gunner", ["ra"]),
     ("gunners", ["ra"]),
     ("gym", ["pe"]),
     ("gypsy", ["rom","chal"]),
     ("gypsy woman", ["chai"]),
     ("hail", ["ave"]),
     ("hairdresser", ["comb"]),
     ("half", ["semi","hf","demi"]),
     ("half an em", ["n"]),
     ("half century", ["l"]),
     ("half day", ["pm","am"]),
     ("half ditch", ["ha"]),
     ("half dozen", ["vi"]),
     ("half dry", ["t"]),
     ("half minute", ["min","mo","ute"]),
     ("hand", ["man","h","l","ab","r"]),
     ("handwriting", ["ms"]),
     ("hard", ["h"]),
     ("hard ground", ["hearth"]),
     ("hard water", ["ice"]),
     ("has", ["s"]),
     ("head", ["ras","pate","ness"]),
     ("healer", ["dr"]),
     ("heart", ["h"]),
     ("heat", ["j"]),
     ("Heath", ["ted"]),
     ("heather", ["ling"]),
     ("Hebrew letter", ["lamed","vau","resh","aleph","beth","teth"]),
     ("hedge", ["haw"]),
     ("height", ["h"]),
     ("helium", ["he"]),
     ("Hell", ["pit","tor","dis"]),
     ("hello", ["hi"]),
     ("henry", ["h"]),
     ("Her Majesty", ["hm"]),
     ("here in Rome", ["hic"]),
     ("here is", ["hs"]),
     ("hesitation", ["er","um","ur"]),
     ("high class", ["ai","u","a"]),
     ("high explosive", ["he"]),
     ("high tension", ["ht"]),
     ("hill", ["mt","tor"]),
     ("hindrance", ["let"]),
     ("hire purchase", ["hp"]),
     ("his", ["s"]),
     ("His Excellency", ["he"]),
     ("His Majesty", ["hm"]),
     ("hole", ["f","o"]),
     ("hollow", ["o"]),
     ("Holy Writ", ["nt","ot"]),
     ("Home Counties", ["se"]),
     ("honey", ["mel"]),
     ("honour", ["obe","ch","om"]),
     ("hoop", ["o"]),
     ("horse", ["cob","nag","arab","gg","h","barb","gee"]),
     ("horse race", ["oaks","national","derby"]),
     ("hospital", ["h"]),
     ("hot", ["h"]),
     ("hour", ["h","hr"]),
     ("house", ["semi","ho","co","cot","h"]),
     ("housekeeper", ["lar"]),
     ("Humberside", ["ne"]),
     ("hundred", ["c","ton","ic"]),
     ("hundred and fifty", ["cl"]),
     ("hundred and one", ["ci"]),
     ("hundred and sixty", ["t"]),
     ("hundred and sixty thousand", ["t"]),
     ("hundred thousand", ["lac","c","lakh"]),
     ("hundreds", ["cs","d"]),
     ("Hungary", ["h"]),
     ("hunter", ["orion"]),
     ("husband", ["h","man"]),
     ("hush", ["st","sh"]),
     ("hydrant", ["h"]),
     ("hydrogen", ["h"]),
     ("hymns", ["am"]),
     ("I", ["ane","an","ay","aye","eye","a"]),
     ("I am", ["am","iam","im"]),
     ("I had", ["id"]),
     ("I have", ["ive"]),
     ("I say", ["eye","aye"]),
     ("I see", ["ic"]),
     ("I shall", ["ill"]),
     ("I would", ["id"]),
     ("I, being French", ["je"]),
     ("Iceland", ["is"]),
     ("identification", ["id"]),
     ("if", ["an"]),
     ("if it", ["ant"]),
     ("illegal army", ["ira","plo","eta"]),
     ("Illinois", ["ill"]),
     ("illiterate's signature", ["x"]),
     ("illness", ["flu"]),
     ("image building", ["pr"]),
     ("imaginary number", ["i"]),
     ("in bed", ["bed"]),
     ("in charge", ["ic"]),
     ("in court", ["up"]),
     ("in fashion", ["in"]),
     ("in good condition", ["go"]),
     ("In Paris, I", ["je"]),
     ("in the afternoon", ["pm"]),
     ("in the main", ["deep"]),
     ("in the modern age", ["ad"]),
     ("in the morning", ["am"]),
     ("in the same place", ["ibid","ib"]),
     ("in the style of", ["ala"]),
     ("in the year of our Lord", ["ad"]),
     ("indeed", ["deed"]),
     ("indefinite number", ["n","no"]),
     ("India", ["ind"]),
     ("individual", ["i"]),
     ("individuality", ["ka"]),
     ("inductance", ["l"]),
     ("inexperienced driver", ["l"]),
     ("infantry", ["foot"]),
     ("inferior", ["b"]),
     ("inferior horse", ["tit"]),
     ("information", ["gen"]),
     ("informer", ["nose","grass"]),
     ("Inn", ["bar"]),
     ("instinct", ["id"]),
     ("integers", ["z"]),
     ("intended", ["ment"]),
     ("international", ["cap","un"]),
     ("international organisation", ["uno"]),
     ("invariably", ["eer"]),
     ("inventor", ["edison"]),
     ("iodine", ["i"]),
     ("iota", ["i"]),
     ("Iowa", ["ia"]),
     ("Iran", ["ir"]),
     ("Ireland", ["irl"]),
     ("Irish house", ["dail"]),
     ("Irish police", ["ruc"]),
     ("iron", ["fe"]),
     ("is", ["est","s"]),
     ("is able to", ["can"]),
     ("island", ["ait","iom","is","man","eyot","i","inch"]),
     ("Isle of Man", ["iom"]),
     ("Israel", ["il"]),
     ("issue", ["son"]),
     ("it", ["sa","a"]),
     ("Italian", ["it"]),
     ("Italian banker", ["po"]),
     ("Italian flower", ["po"]),
     ("Italy", ["i"]),
     ("ivy", ["iv"]),
     ("izzard", ["z"]),
     ("Jack", ["j"]),
     ("jade", ["yu"]),
     ("Jamaica", ["ja"]),
     ("jammed cylinder", ["swiss roll"]),
     ("Japan", ["j"]),
     ("jay", ["j"]),
     ("jazz fan", ["cat"]),
     ("jelly", ["gel"]),
     ("jolly", ["rm"]),
     ("joule", ["j"]),
     ("journalist", ["ed"]),
     ("joyful cry", ["io"]),
     ("judge", ["j"]),
     ("junction", ["t"]),
     ("justice", ["j"]),
     ("kale", ["kl"]),
     ("kappa", ["k"]),
     ("Kay", ["k"]),
     ("Kelt", ["q","p"]),
     ("kelvin", ["k"]),
     ("Kentucky", ["ky"]),
     ("kewpie", ["qp"]),
     ("key", ["c","f","d","e","a","g","b"]),
     ("Khmer Republic", ["k"]),
     ("kick off", ["ko"]),
     ("killer", ["cain"]),
     ("kilo", ["k"]),
     ("kilometre", ["km"]),
     ("king", ["k","gr","hm","lear","cr","roi","r","sm","er"]),
     ("king emperor", ["ri"]),
     ("King George", ["gr"]),
     ("Kirkpatrick", ["k"]),
     ("kiss", ["x"]),
     ("knave", ["j"]),
     ("knew", ["wist"]),
     ("knight", ["kt","k","sir","n"]),
     ("knock out", ["ko"]),
     ("Koechel", ["k"]),
     ("koppa", ["q"]),
     ("krypton", ["kr"]),
     ("label", ["tag","tab"]),
     ("laboratory", ["lab"]),
     ("Labour", ["lab","l"]),
     ("lady", ["eve","dame","she"]),
     ("lake", ["erie","loch","l"]),
     ("lambda", ["l"]),
     ("lambert", ["l"]),
     ("landline", ["ry","br","rly"]),
     ("large amount", ["ton","lot"]),
     ("large letters", ["os"]),
     ("largesse", ["s"]),
     ("last character", ["z"]),
     ("last letter", ["omega","z"]),
     ("last month", ["ult","dec"]),
     ("last word", ["obit","rip","amen"]),
     ("late", ["ex"]),
     ("latin", ["l"]),
     ("latitude", ["l"]),
     ("laugh", ["haha","hehe","ha"]),
     ("lawgiver", ["moses"]),
     ("lawman", ["earp","bl","da"]),
     ("Lawrence", ["te"]),
     ("lawyer", ["bl","da"]),
     ("lawyers", ["bar"]),
     ("layer", ["hen","e"]),
     ("lead", ["pb"]),
     ("leading", ["noi"]),
     ("league", ["l"]),
     ("learner", ["l"]),
     ("learning", ["l"]),
     ("leave", ["part"]),
     ("leaves", ["tea"]),
     ("left", ["l","port"]),
     ("left hand", ["vo","lh"]),
     ("leftist", ["red"]),
     ("leg", ["on"]),
     ("legal document", ["deed"]),
     ("legate", ["he"]),
     ("length", ["ell","l"]),
     ("lettuce", ["cos"]),
     ("level", ["a","y"]),
     ("Liberal", ["l","lib"]),
     ("Libya", ["lar"]),
     ("licentiate", ["l"]),
     ("Lieutenant", ["lt"]),
     ("life symbol", ["ankh"]),
     ("light", ["very"]),
     ("like", ["as"]),
     ("limb", ["leg","arm"]),
     ("Lincoln", ["abe"]),
     ("line", ["row","l","i","ry"]),
     ("liner", ["ss"]),
     ("lines", ["ry","br","rly"]),
     ("lira", ["l"]),
     ("lire", ["l"]),
     ("listener", ["ear"]),
     ("litre", ["l"]),
     ("little", ["wee"]),
     ("little devil", ["imp"]),
     ("little horse", ["gg","ned","gee","nag"]),
     ("little way", ["st","rd","ry"]),
     ("little woman", ["jo"]),
     ("live", ["l","be"]),
     ("lived so long", ["av"]),
     ("loaded", ["lit"]),
     ("local", ["ph","inn","pub"]),
     ("loch", ["ness"]),
     ("lock keeper", ["hair net"]),
     ("logarithm base", ["e"]),
     ("London Area", ["se"]),
     ("London district", ["ec"]),
     ("long", ["l"]),
     ("long playing", ["lp"]),
     ("long time", ["age"]),
     ("look", ["v","see","la","vide","lo"]),
     ("looker", ["eye"]),
     ("loop", ["o"]),
     ("Los Angeles", ["la"]),
     ("lot", ["d","m","c"]),
     ("loud", ["f"]),
     ("Louisiana", ["la"]),
     ("love", ["o","nil"]),
     ("low", ["moo"]),
     ("low down", ["gen"]),
     ("low grade", ["e"]),
     ("lower", ["cow"]),
     ("lumen", ["l"]),
     ("luminance", ["l"]),
     ("lunchtime", ["one","i"]),
     ("Luxembourg", ["l"]),
     ("magnesium", ["mg"]),
     ("magnetic flux", ["b"]),
     ("maiden", ["over","io","m"]),
     ("maiden over", ["m"]),
     ("mailboat", ["rms"]),
     ("main", ["sea","deep"]),
     ("main road", ["ai","mi"]),
     ("male", ["m","he","him"]),
     ("Malta", ["m"]),
     ("man", ["isle","iom","g","vir","m"]),
     ("manage", ["run"]),
     ("managed", ["ran"]),
     ("management", ["admin"]),
     ("manuscript", ["ms"]),
     ("manuscripts", ["mss"]),
     ("many", ["l","c","m","d"]),
     ("mare", ["m"]),
     ("Marine", ["jolly","rm"]),
     ("mark", ["m","d","dm"]),
     ("mark of the beast", ["mb"]),
     ("married", ["m"]),
     ("Marshal", ["ney"]),
     ("masculine", ["m"]),
     ("mass", ["m"]),
     ("Massachusetts", ["mass"]),
     ("master", ["ma","m"]),
     ("Master of Arts", ["ma"]),
     ("master of ceremonies", ["mc"]),
     ("match", ["test"]),
     ("maths function", ["log","tan","sine"]),
     ("mature", ["age"]),
     ("Mayfair", ["wi"]),
     ("meal ticket", ["lv"]),
     ("meant", ["ment"]),
     ("measure", ["ell","ft","m","em","el","en","yd","y"]),
     ("medal", ["td","mc","mm"]),
     ("meeting", ["agm"]),
     ("member", ["leg","arm","toe","m","mp"]),
     ("member of parliament", ["mp"]),
     ("memory", ["rom","ram"]),
     ("men", ["or"]),
     ("Merchant Navy", ["mn"]),
     ("Merchant of Venice", ["polo"]),
     ("mercury", ["hg"]),
     ("Merseyside", ["nw"]),
     ("meso-", ["m"]),
     ("meta-", ["m"]),
     ("meter", ["m"]),
     ("metre", ["m"]),
     ("midday", ["a","m","n"]),
     ("midnight", ["g"]),
     ("mile", ["m"]),
     ("military police", ["mp"]),
     ("miller's corn", ["grist"]),
     ("miners", ["num"]),
     ("minor", ["wee"]),
     ("misanthrope", ["timon"]),
     ("mischevious child", ["imp"]),
     ("mischief", ["ate"]),
     ("missiles", ["ammo"]),
     ("Mississippi", ["miss"]),
     ("Missouri", ["mo"]),
     ("mister", ["mr"]),
     ("model", ["t"]),
     ("modern journalism", ["eng"]),
     ("modern times", ["ad"]),
     ("modulus", ["m"]),
     ("mole", ["spy","pier"]),
     ("monarch", ["k","r","er"]),
     ("Monday", ["mon","m"]),
     ("money", ["tin","cent","m","l","brass"]),
     ("monsieur", ["m"]),
     ("monstrous regiment", ["women"]),
     ("month", ["mo","r","m"]),
     ("months", ["mos"]),
     ("moon", ["m"]),
     ("morning", ["am"]),
     ("moth", ["y"]),
     ("mother", ["mum","ma","dam","mam"]),
     ("motor race", ["carnation"]),
     ("motoring organisation", ["aa","rac"]),
     ("motorway", ["m","mi"]),
     ("mountain", ["mt","tor","alp"]),
     ("mountain retreat", ["pla"]),
     ("mountaineer", ["sherpa"]),
     ("mounted", ["up"]),
     ("mounted police", ["mp"]),
     ("mountie", ["mp"]),
     ("mounties", ["mp"]),
     ("mouthpiece", ["lips"]),
     ("Mozart's works", ["k"]),
     ("mu", ["m"]),
     ("murder victim", ["abel"]),
     ("murderer", ["cain"]),
     ("music school", ["ram"]),
     ("Muslim leader", ["aga"]),
     ("name", ["n"]),
     ("name unknown", ["nu"]),
     ("named", ["dit"]),
     ("namely", ["sc"]),
     ("national", ["n"]),
     ("nationalist", ["n"]),
     ("nationalists", ["sdp"]),
     ("native", ["abo"]),
     ("naught", ["o"]),
     ("naval commander", ["corn"]),
     ("Navy", ["rn"]),
     ("near", ["nie"]),
     ("neat", ["cow","ox","kine","cattle"]),
     ("neat sound", ["lowing","moo"]),
     ("neck", ["col","v"]),
     ("neckline", ["v"]),
     ("neon", ["ne"]),
     ("neper", ["n"]),
     ("network", ["rete"]),
     ("neuter", ["n"]),
     ("neutral", ["n"]),
     ("never-never", ["hp"]),
     ("new", ["n"]),
     ("new driver", ["l"]),
     ("New Jersey", ["nj"]),
     ("New Orleans", ["no"]),
     ("New Testament", ["nt"]),
     ("New York", ["gotham","ny"]),
     ("New York opera", ["met"]),
     ("newspaper", ["sun","ft"]),
     ("newton", ["n"]),
     ("next month", ["prox"]),
     ("nickel", ["ni"]),
     ("nil", ["o"]),
     ("nine", ["ix"]),
     ("ninety", ["xc","n","q"]),
     ("ninety nine", ["ic"]),
     ("ninety thousand", ["n","q"]),
     ("nitrogen", ["n"]),
     ("no", ["o","nae","non","na"]),
     ("no date", ["nd"]),
     ("no good", ["ng","us"]),
     ("no one", ["noi"]),
     ("no way", ["ord"]),
     ("nobleman", ["don"]),
     ("noisy", ["f"]),
     ("non-commissioned officer", ["rsm","sgt","sm","nco"]),
     ("non-commissioned officers", ["or"]),
     ("noon", ["n","m"]),
     ("north", ["n"]),
     ("North America", ["na"]),
     ("North Dakota", ["nd"]),
     ("North Pole", ["np"]),
     ("north-east", ["ne"]),
     ("north-west", ["nw"]),
     ("northern", ["n"]),
     ("Northern Ireland", ["ni"]),
     ("Northern Territories", ["nt"]),
     ("Norway", ["n"]),
     ("not", ["nae","na","ne"]),
     ("not at home", ["out"]),
     ("not clear", ["nl"]),
     ("not dated", ["nd"]),
     ("not far", ["nl"]),
     ("not out", ["no","in"]),
     ("not permitted", ["nl"]),
     ("not specific", ["ns"]),
     ("nota bene", ["nb"]),
     ("notch", ["v"]),
     ("note", ["nb","lah","a","me","re","tic","soh","doh","te","g","ti","la","n","c","b","f","si","d","mi","fah","so","e","do","fa","ut","sol"]),
     ("nothing", ["o","nil"]),
     ("nothing to America", ["ous"]),
     ("notice", ["d","ad"]),
     ("nought", ["o"]),
     ("noun", ["n"]),
     ("novel", ["she"]),
     ("novice", ["l"]),
     ("now", ["anon","ad"]),
     ("nowadays", ["ad"]),
     ("nu", ["n"]),
     ("number", ["n","ether","d","pin","no"]),
     ("number one", ["noi","ein","uno","i","un","adam","une","me","una"]),
     ("number one returning", ["ion"]),
     ("number plate", ["l"]),
     ("nurse", ["srn","vad"]),
     ("objector", ["co"]),
     ("occupational therapy", ["ot"]),
     ("odds", ["sp"]),
     ("of", ["de"]),
     ("of the", ["dela","del","du","des"]),
     ("offensive", ["tet"]),
     ("office", ["loo","den"]),
     ("officer", ["co","lt"]),
     ("officer commanding", ["oc"]),
     ("officer in charge", ["oic"]),
     ("ogee", ["og"]),
     ("oh", ["o"]),
     ("oh, why", ["oy"]),
     ("Ohio", ["o"]),
     ("ohs", ["oo","os"]),
     ("okay", ["ok"]),
     ("old age", ["eld"]),
     ("old Bob", ["s"]),
     ("old boy", ["ob"]),
     ("old city", ["ur","troy"]),
     ("Old Contemptibles", ["bef"]),
     ("old English", ["oe"]),
     ("old Etonian", ["oe"]),
     ("old fiddle", ["gue","gu"]),
     ("old fighter", ["gladiator"]),
     ("old goat", ["gate"]),
     ("old injury", ["teen","tene"]),
     ("old Irish magistrate", ["rm"]),
     ("old king", ["offa","cole","lud"]),
     ("old man", ["dad","pop","pa"]),
     ("old paint", ["limn"]),
     ("old penny", ["d"]),
     ("old people", ["iceni"]),
     ("old Prime Minister", ["pitt","eden"]),
     ("old railway", ["sr","lner"]),
     ("old scholar", ["erasmus"]),
     ("old shilling", ["s","bob"]),
     ("old ship", ["argo"]),
     ("old style", ["os"]),
     ("Old Testament", ["ot"]),
     ("old thing", ["res"]),
     ("old way", ["via"]),
     ("old way of dating", ["auc"]),
     ("old wedding", ["bridal"]),
     ("old woman", ["ma"]),
     ("omega", ["z"]),
     ("omicron", ["o"]),
     ("on", ["leg"]),
     ("on purpose", ["ment"]),
     ("on the menu", ["on"]),
     ("on the wagon", ["tt"]),
     ("on view to all", ["u"]),
     ("one", ["i","un","an","a","j","ane","ace"]),
     ("one answer", ["ians"]),
     ("one fifteen", ["aside"]),
     ("one hundred and fifty", ["y"]),
     ("one hundred and fifty thousand", ["y"]),
     ("one member", ["amp","imp"]),
     ("one pound", ["alb","al","il","l","lb","ilb"]),
     ("one thousand five hundred", ["md"]),
     ("one time", ["ex"]),
     ("one's", ["as","is"]),
     ("Open University", ["ou"]),
     ("opener", ["key"]),
     ("opening", ["o"]),
     ("operating", ["on"]),
     ("operation", ["op"]),
     ("opposing", ["v"]),
     ("opposite", ["op"]),
     ("opus", ["op"]),
     ("orb", ["o"]),
     ("orchestra", ["lso"]),
     ("order", ["obe","ch","po","om"]),
     ("Ordinary Seaman", ["os"]),
     ("organ", ["ear"]),
     ("orient", ["e"]),
     ("oriental", ["e","ine"]),
     ("ortho-", ["o"]),
     ("otorhinolaryngology", ["ent"]),
     ("ought", ["o"]),
     ("ounce", ["oz"]),
     ("our era", ["ad"]),
     ("our islands", ["gb"]),
     ("our man", ["he"]),
     ("our time", ["ad"]),
     ("out of print", ["op"]),
     ("outdated hairdo", ["da"]),
     ("outlaw", ["ban"]),
     ("outsize", ["os"]),
     ("over", ["supra","re"]),
     ("overhead railway", ["l"]),
     ("owe", ["o"]),
     ("owes", ["os","oo"]),
     ("own", ["ain"]),
     ("own goal", ["og"]),
     ("ox", ["neat","kine"]),
     ("Oxford dreamer", ["spire"]),
     ("oxygen", ["o"]),
     ("page", ["p"]),
     ("pages", ["pp"]),
     ("painter", ["ra","ara","ney","pra"]),
     ("painting", ["art"]),
     ("pair", ["pr"]),
     ("palladium", ["po"]),
     ("Panama", ["pa"]),
     ("paper", ["ms","b","a"]),
     ("papers", ["mss"]),
     ("paradise", ["eden"]),
     ("paragon", ["saint","s","st"]),
     ("park", ["p"]),
     ("parking", ["p"]),
     ("part", ["pt"]),
     ("part of Bible", ["nt","ot"]),
     ("part of collar", ["s"]),
     ("participle", ["p"]),
     ("particle", ["x"]),
     ("partnership", ["we","sn","ew","ns"]),
     ("party", ["con","lib","do","lab","tory"]),
     ("pass", ["col"]),
     ("pawn", ["p"]),
     ("paying guest", ["pg"]),
     ("pea", ["p"]),
     ("peacekeepers", ["un"]),
     ("peacemakers", ["acas"]),
     ("peak", ["alp"]),
     ("peas", ["pp","ps"]),
     ("peavy", ["pv"]),
     ("pedal", ["p"]),
     ("pee", ["p"]),
     ("pees", ["pp","ps"]),
     ("peg", ["tee","t","p"]),
     ("pellet", ["o"]),
     ("pen", ["j"]),
     ("penny", ["d","p"]),
     ("people", ["race","men","nation"]),
     ("per", ["a"]),
     ("perfect letter", ["t"]),
     ("performance", ["act"]),
     ("performing", ["on"]),
     ("period", ["age","bc","ad"]),
     ("permit", ["let"]),
     ("permitted", ["let"]),
     ("Peru", ["pe"]),
     ("philosopher", ["plato","bacon"]),
     ("phosphorous", ["p"]),
     ("physical education", ["pe"]),
     ("physical training", ["pt"]),
     ("pi", ["p"]),
     ("pianissimo", ["pp"]),
     ("piano", ["p"]),
     ("piece", ["bit","pawn","man"]),
     ("pilot", ["george","ace"]),
     ("pint", ["p","pt"]),
     ("Planck's constant", ["h"]),
     ("plate", ["t"]),
     ("platinum", ["pt"]),
     ("play", ["noh","no"]),
     ("playing", ["in","on"]),
     ("plotters' street", ["cato"]),
     ("Pluto", ["dis"]),
     ("PM's address", ["ten","x"]),
     ("poet", ["ae"]),
     ("point", ["head","e","ness","tor","s","pt","w","n"]),
     ("poise", ["p"]),
     ("Poland", ["pl"]),
     ("pole", ["rod","po","sp","np","s","n"]),
     ("police", ["force","met","cid"]),
     ("policeman", ["pc","mp"]),
     ("politician", ["con","mp","lib","lab","tory"]),
     ("poor actor", ["ham"]),
     ("poor horse", ["tit","rosinante"]),
     ("port", ["rio","l","aden"]),
     ("port authority", ["pla"]),
     ("Portugal", ["p"]),
     ("posh", ["u"]),
     ("Post Office", ["po"]),
     ("post town", ["pt"]),
     ("postscript", ["ps"]),
     ("potassium", ["k"]),
     ("pound", ["lb","lam","ezra","l"]),
     ("power", ["p","vis"]),
     ("practice", ["use"]),
     ("practise", ["use"]),
     ("present day", ["ad"]),
     ("preservationists", ["nt"]),
     ("president", ["pres","p","pr","chair"]),
     ("pretty girl", ["cutie","dish"]),
     ("prevent", ["bar"]),
     ("price", ["pr"]),
     ("priest", ["pr","eli","abbe","rev","cure"]),
     ("primate", ["ape"]),
     ("Prime Minister", ["pm"]),
     ("primitive", ["ur"]),
     ("prince", ["p","pr","ras"]),
     ("princess", ["ina","regan","ida","anne","di"]),
     ("printer's measure", ["em","el","en"]),
     ("prison", ["bird","jug","quad","cooler","pen","nick","hock","stir","can"]),
     ("private", ["gi"]),
     ("prohibition", ["ban"]),
     ("prominence", ["tor"]),
     ("promises to pay", ["ious"]),
     ("promotion", ["ad"]),
     ("prophet", ["eli"]),
     ("provided", ["if"]),
     ("providing", ["if"]),
     ("psychotic state", ["dt"]),
     ("public relations", ["pr"]),
     ("public relations officer", ["pro"]),
     ("Puerto Rico", ["pr"]),
     ("puff", ["ad"]),
     ("pupil", ["l"]),
     ("pure", ["net"]),
     ("put", ["set"]),
     ("put on", ["don"]),
     ("QE", ["er"]),
     ("quality", ["q"]),
     ("quart", ["qt","qu"]),
     ("quarter", ["e","s","sw","w","n","nw","ne","se"]),
     ("Quebec", ["q"]),
     ("queen", ["r","hm","q","qu","er","mab","bess"]),
     ("Queensland", ["q"]),
     ("query", ["q"]),
     ("question", ["q"]),
     ("queue", ["cue","q"]),
     ("quiet", ["p","mum","sh","qt"]),
     ("quintal", ["q"]),
     ("rabbi", ["r"]),
     ("rabbit", ["brer"]),
     ("race", ["nation","tt"]),
     ("radius", ["r"]),
     ("rage", ["ire"]),
     ("rail", ["ry","t"]),
     ("railway", ["br","rly","l","ry"]),
     ("railways", ["br"]),
     ("rain", ["r"]),
     ("rand", ["r"]),
     ("rare", ["r"]),
     ("rate", ["mph"]),
     ("rating", ["ab"]),
     ("rational numbers", ["q"]),
     ("ray", ["x"]),
     ("reading", ["r"]),
     ("ready", ["set","go"]),
     ("real numbers", ["r"]),
     ("Reaumur", ["r"]),
     ("recipe", ["r","rec"]),
     ("record", ["log","disc","entry","cd","lp","ep"]),
     ("rector", ["r"]),
     ("refusal", ["no"]),
     ("Regina", ["r"]),
     ("relation", ["sib"]),
     ("relationship", ["pi"]),
     ("relative", ["rel"]),
     ("religious", ["pi"]),
     ("religious education", ["re"]),
     ("remains", ["ash"]),
     ("reported", ["dit"]),
     ("representative", ["mp"]),
     ("Republican", ["r"]),
     ("reserves", ["ta"]),
     ("resident magistrate", ["rm"]),
     ("resistance", ["r"]),
     ("restrain", ["dam"]),
     ("retreat", ["den"]),
     ("rev up", ["ver"]),
     ("revolutionary", ["che","red"]),
     ("Rex", ["r"]),
     ("rho", ["r"]),
     ("Rhode Island", ["ri"]),
     ("riding", ["up"]),
     ("right", ["r","rt"]),
     ("right hand", ["rh","ro"]),
     ("Right Reverend", ["rr"]),
     ("ring", ["disc","o"]),
     ("ring road", ["ord"]),
     ("river", ["po","isis","ure","cam","ea","dee","r","alph","aire","fal","tay","exe","ouse","tees"]),
     ("road", ["ave","r","a","rd","st"]),
     ("Rolls Royce", ["rr"]),
     ("Roman", ["vir"]),
     ("Roman Catholic", ["rc"]),
     ("Roman people", ["pr"]),
     ("Romania", ["r"]),
     ("Romans", ["rom","pr"]),
     ("Romeo", ["r"]),
     ("rontgen unit", ["r"]),
     ("roof", ["m"]),
     ("rook", ["r"]),
     ("roughly", ["c","ca"]),
     ("round", ["o"]),
     ("row", ["ado","tier"]),
     ("rowing boat", ["eight","four"]),
     ("royal", ["r"]),
     ("Royal Academician", ["ra"]),
     ("Royal Academy", ["ra"]),
     ("Royal Artillery", ["ra"]),
     ("royal badge", ["er"]),
     ("Royal Engineer", ["re"]),
     ("Royal Engineers", ["re"]),
     ("Royal Marine", ["rm"]),
     ("Royal Marines", ["rm"]),
     ("Royal Navy", ["rn"]),
     ("rubber", ["ule"]),
     ("rubbish", ["rot","tat"]),
     ("rugby", ["ru"]),
     ("run", ["r"]),
     ("runner", ["river"]),
     ("running", ["admin"]),
     ("running water", ["ea"]),
     ("Russian river", ["ob"]),
     ("Sabbath", ["s"]),
     ("said", ["idem","dit"]),
     ("sailor", ["tar","os","ab","jack"]),
     ("sailors", ["rn"]),
     ("saint", ["s","st"]),
     ("saints", ["sts","ss"]),
     ("salesman", ["rep"]),
     ("salt", ["ab","jack","tar"]),
     ("same", ["do","id"]),
     ("same place", ["ib"]),
     ("Sandhurst", ["rma"]),
     ("sapper", ["re"]),
     ("sappers", ["re"]),
     ("Saturday", ["s","sat"]),
     ("save", ["bar"]),
     ("say", ["dit"]),
     ("scab", ["rat"]),
     ("Scarlatti's works", ["k"]),
     ("Schmieder", ["s"]),
     ("scholar", ["ma","ba"]),
     ("school", ["eton"]),
     ("Schubert's works", ["d"]),
     ("science centre", ["lab"]),
     ("scope, plenty of", ["az"]),
     ("scorer", ["composer"]),
     ("Scot", ["mon","jock","mac","ian"]),
     ("Scotsman", ["jock","mac","ian","mon"]),
     ("screecher", ["swift"]),
     ("scriptures", ["nt","ot"]),
     ("scruple", ["scr"]),
     ("sea", ["main","c","mer","deep"]),
     ("Seabee", ["cb"]),
     ("seaman", ["ab","jack","tar"]),
     ("seas", ["cc","cs"]),
     ("second", ["sec","mo","b","s"]),
     ("second child", ["abel"]),
     ("second class", ["b"]),
     ("second letter", ["b"]),
     ("second thoughts", ["ps"]),
     ("second-hand", ["sh"]),
     ("secret service", ["cia"]),
     ("secretary", ["temp"]),
     ("see", ["vid","c","v","vide","lo","ely"]),
     ("see why", ["cy"]),
     ("see you", ["cu"]),
     ("seedy", ["cd"]),
     ("seer", ["eye","optic"]),
     ("self-confessed", ["iam","am","im"]),
     ("self-contained", ["sc"]),
     ("senior", ["sr"]),
     ("sergeant", ["nco","sgt"]),
     ("service", ["rn","rm","ace","raf","let","mass"]),
     ("serving man", ["gi"]),
     ("settled", ["lit"]),
     ("seven", ["s","z"]),
     ("seven thousand", ["s","z"]),
     ("sex appeal", ["it","sa"]),
     ("shares", ["scrip"]),
     ("shark", ["nurse"]),
     ("sheep", ["ram"]),
     ("shilling", ["s"]),
     ("ship", ["ss"]),
     ("shipping company", ["line"]),
     ("shirt", ["t"]),
     ("short answer", ["ans"]),
     ("short break", ["hol"]),
     ("short time", ["t","sec","mo"]),
     ("show-ring", ["manifesto"]),
     ("side", ["xi","l","s","r","xv"]),
     ("siemens", ["s"]),
     ("sign", ["v"]),
     ("sign of love", ["x"]),
     ("sign of the times", ["x"]),
     ("silence", ["mum","st","sh","tace"]),
     ("silicon", ["si"]),
     ("silver", ["ag"]),
     ("simple", ["herb"]),
     ("sin", ["err"]),
     ("single", ["i"]),
     ("sister", ["sis","s"]),
     ("six", ["vi"]),
     ("six-footer", ["ant","bee","insect"]),
     ("sixpence", ["vid","vip"]),
     ("sixth sense", ["esp"]),
     ("skill", ["art"]),
     ("skipping", ["omitting"]),
     ("sling", ["ign","ing"]),
     ("sloth", ["ai"]),
     ("small", ["tiny","wee"]),
     ("small capitals", ["sc"]),
     ("small change", ["p"]),
     ("small illustration", ["fig"]),
     ("small measure", ["cc","em","el","en"]),
     ("small quantity", ["cc"]),
     ("small square", ["m","em"]),
     ("small weight", ["wt","oz","gr","ct"]),
     ("smuggle", ["run"]),
     ("smuggled", ["ran"]),
     ("snake", ["asp","boa"]),
     ("snoring", ["zz"]),
     ("snow", ["s"]),
     ("so", ["ergo"]),
     ("soak", ["ret"]),
     ("soccer blunder", ["og"]),
     ("social worker", ["ant","bee"]),
     ("socialist", ["red"]),
     ("socially acceptable", ["u"]),
     ("society", ["s"]),
     ("sodium", ["na"]),
     ("sofly", ["pp"]),
     ("soft", ["p","b","pp"]),
     ("softly", ["p"]),
     ("soldier", ["ant","man","ney","gi"]),
     ("soldiers", ["ra","re","men","ta","sas","impi","or"]),
     ("solver", ["you"]),
     ("son", ["s"]),
     ("song", ["lay","aria","air"]),
     ("sons", ["s"]),
     ("soprano", ["sop","s"]),
     ("sound of sleep", ["z"]),
     ("sound of snoring", ["zz"]),
     ("source", ["parent"]),
     ("south", ["s"]),
     ("South Africa", ["sa"]),
     ("South America", ["sa"]),
     ("South Dakota", ["sd"]),
     ("South Island", ["si"]),
     ("South Pole", ["sp"]),
     ("south-east", ["se"]),
     ("south-west", ["sw"]),
     ("southern", ["s"]),
     ("sovereign", ["l"]),
     ("Soviet Union", ["ussr","su"]),
     ("space", ["s"]),
     ("spade", ["s"]),
     ("Spain", ["e"]),
     ("spangle", ["o"]),
     ("spanish hero", ["cid"]),
     ("spasm", ["tic"]),
     ("speakers", ["lips"]),
     ("species", ["sp"]),
     ("specifically", ["as","sc"]),
     ("spectacles", ["oo"]),
     ("spectator", ["eye"]),
     ("speculator", ["stag","bear"]),
     ("speed", ["rate","mph"]),
     ("speed of light", ["c"]),
     ("spies", ["cia"]),
     ("spike", ["ear"]),
     ("sports car", ["rod","gt"]),
     ("spot marked", ["x"]),
     ("spring", ["spa","c"]),
     ("spy", ["agent"]),
     ("spymaster", ["m"]),
     ("square", ["t","s"]),
     ("square root of -1", ["j","i"]),
     ("stand-in", ["sub"]),
     ("standard", ["par"]),
     ("starting price", ["sp"]),
     ("steamship", ["ss"]),
     ("step", ["pas"]),
     ("stokes", ["s","st"]),
     ("stone", ["st"]),
     ("stop", ["colon","pt"]),
     ("straight line", ["i"]),
     ("street", ["rue","st"]),
     ("strikebreaker", ["rat"]),
     ("string", ["g","d","a","e"]),
     ("strings", ["d","a","g"]),
     ("strong", ["f"]),
     ("student", ["l"]),
     ("students", ["nus"]),
     ("students' union", ["nus"]),
     ("study", ["den","con"]),
     ("stumped", ["st"]),
     ("stunner", ["ko"]),
     ("submariner", ["nemo"]),
     ("substitute", ["sub"]),
     ("succeeded", ["s"]),
     ("success", ["go"]),
     ("suit", ["g"]),
     ("suitable for children", ["u"]),
     ("sulphur", ["s"]),
     ("sum", ["add"]),
     ("summer", ["bst"]),
     ("summer time", ["bst"]),
     ("sun", ["s","ra"]),
     ("sun god", ["ra"]),
     ("sun-god", ["sol"]),
     ("Sunday School", ["ss"]),
     ("superior", ["u","up"]),
     ("support", ["bra","leg"]),
     ("supposed force", ["od"]),
     ("surgeon", ["vet"]),
     ("Sweden", ["s"]),
     ("sweetheart", ["jo"]),
     ("swimmer", ["eel","ling","cod"]),
     ("swindle", ["con"]),
     ("Switzerland", ["ch"]),
     ("take", ["r","rec"]),
     ("tales", ["ana"]),
     ("tanner", ["vid","vip"]),
     ("Tantalus' prisoner", ["decanter"]),
     ("Tanzania", ["eat"]),
     ("tap", ["h","c"]),
     ("tar", ["ab"]),
     ("tau", ["t"]),
     ("tax", ["scot","vat"]),
     ("tax officer", ["to"]),
     ("te", ["t"]),
     ("tea", ["cha","t"]),
     ("tea-time", ["iv"]),
     ("teachers", ["nut"]),
     ("team", ["xv","xi","side"]),
     ("teas", ["ts","tt"]),
     ("tee", ["t","peg"]),
     ("teepee", ["tp"]),
     ("tees", ["ts","tt"]),
     ("teetotal", ["tt"]),
     ("teetotaller", ["tt"]),
     ("telepathy", ["esp"]),
     ("ten", ["io","x"]),
     ("ten thousand", ["x"]),
     ("tenor", ["t"]),
     ("terriers", ["ta"]),
     ("Territorial Army", ["ta"]),
     ("territorials", ["ta"]),
     ("terrorists", ["ira","plo","provos","eta"]),
     ("tesla", ["t"]),
     ("test", ["oral","mot"]),
     ("text", ["ms"]),
     ("Thailand", ["t"]),
     ("thank you", ["ta","tt"]),
     ("thanks", ["ta"]),
     ("that", ["yt","id"]),
     ("that is", ["ie","sc"]),
     ("that's", ["ie"]),
     ("the", ["der","el","t","la","die","ye","das","le","il"]),
     ("the French", ["le","la","les"]),
     ("the German", ["die","der"]),
     ("the greatest", ["ali"]),
     ("the man", ["he"]),
     ("the pope", ["hh"]),
     ("the same", ["do"]),
     ("the Spanish", ["el"]),
     ("the thing", ["it","play"]),
     ("the woman", ["she"]),
     ("the woman's", ["her"]),
     ("them", ["em"]),
     ("theologian", ["bd","dd"]),
     ("theory", ["ism"]),
     ("therefore", ["so"]),
     ("third man", ["abel"]),
     ("thirty seconds", ["min"]),
     ("this", ["hic","cet","ce"]),
     ("this country", ["uk"]),
     ("this era", ["ad"]),
     ("this island", ["uk"]),
     ("this month", ["inst"]),
     ("this year", ["ha"]),
     ("thoroughfare", ["st"]),
     ("thousand", ["g","x","k","m"]),
     ("three", ["tri","ter"]),
     ("three hundred", ["b"]),
     ("three thousand", ["b"]),
     ("three times a day", ["tid"]),
     ("thrice", ["tri","ter"]),
     ("through", ["per"]),
     ("thus", ["sic","so"]),
     ("time", ["t","eon","sec","mo","age"]),
     ("times", ["by","x"]),
     ("tin", ["sn"]),
     ("tinker", ["sly"]),
     ("to the", ["aux","ala","au"]),
     ("today", ["ad"]),
     ("ton", ["t"]),
     ("tonne", ["t"]),
     ("torpedo boat", ["tb","mtb"]),
     ("Tosti's song", ["tata"]),
     ("tot", ["add"]),
     ("touching", ["re"]),
     ("track", ["y"]),
     ("tradesmen", ["tu"]),
     ("traffic signal", ["go","stop"]),
     ("trainee", ["l"]),
     ("training", ["pt","pe"]),
     ("trains", ["br"]),
     ("tramp", ["hobo"]),
     ("transaction", ["tr"]),
     ("transatlantic", ["us"]),
     ("translation", ["tr"]),
     ("transport", ["bus","cab","rly","ry","cart","br","tram","car"]),
     ("trap", ["u"]),
     ("traveller", ["rom","rep"]),
     ("tree", ["actor","yew","fir","ash"]),
     ("tree ring", ["mayo"]),
     ("trendy", ["in"]),
     ("tribe", ["dan","gad"]),
     ("trick", ["con"]),
     ("triple", ["tri","ter"]),
     ("tritium", ["t"]),
     ("triumphant cry", ["io"]),
     ("trivial sum", ["ip"]),
     ("troops", ["re"]),
     ("trouble", ["ail","ado"]),
     ("Troy", ["t"]),
     ("tube", ["u"]),
     ("Tuesday", ["t"]),
     ("tune", ["air"]),
     ("tungsten", ["w"]),
     ("Turkey", ["tr"]),
     ("turn", ["u"]),
     ("twenty", ["k"]),
     ("twenty feet", ["rope"]),
     ("twenty five pounds", ["pony"]),
     ("twenty thousand", ["k"]),
     ("twenty-five pounds", ["pony"]),
     ("twice", ["bis"]),
     ("twitching", ["tic"]),
     ("two", ["bi","ii","di","pr","bis"]),
     ("two hundred", ["h","cc"]),
     ("two hundred and fifty", ["k","e"]),
     ("two hundred and fifty thousand", ["e"]),
     ("two hundred thousand", ["h"]),
     ("Tyneside", ["ne"]),
     ("tyro", ["l"]),
     ("U-boat", ["sub"]),
     ("Ulster", ["ni"]),
     ("un", ["an","i","a"]),
     ("uncle", ["pawnbroker","eme","sam"]),
     ("undergarment", ["bra"]),
     ("undersecretary", ["us"]),
     ("understood", ["ment"]),
     ("underworld", ["dis"]),
     ("undivided", ["one"]),
     ("unfashionable", ["out","square"]),
     ("unfavourable aspect", ["n"]),
     ("unidentified", ["nu"]),
     ("union", ["u"]),
     ("Unionist", ["u"]),
     ("unit", ["i","a"]),
     ("United Kingdom", ["uk"]),
     ("United Nations", ["un"]),
     ("universal", ["u"]),
     ("universal set", ["e"]),
     ("university", ["u"]),
     ("university teacher", ["don"]),
     ("unknown", ["x","z","y"]),
     ("unknown number", ["n"]),
     ("unlimited number", ["n"]),
     ("unpaid", ["hon"]),
     ("unservicable", ["us"]),
     ("unwell", ["ill"]),
     ("upper class", ["u"]),
     ("uppish", ["u"]),
     ("upright", ["i","pi"]),
     ("upsilon", ["u"]),
     ("uranium", ["u"]),
     ("Uruguay", ["uru","u"]),
     ("us", ["s"]),
     ("use", ["uu","us"]),
     ("used", ["sh"]),
     ("useless", ["us"]),
     ("Utah", ["u"]),
     ("vacant", ["e"]),
     ("vanadium", ["v"]),
     ("various years", ["vy"]),
     ("Vatican", ["v"]),
     ("vee", ["v"]),
     ("velocity", ["v"]),
     ("verb", ["vb","v"]),
     ("verse", ["v"]),
     ("versus", ["v"]),
     ("very", ["tres","unco","v"]),
     ("very black", ["bb"]),
     ("very hard", ["hh"]),
     ("very large", ["os"]),
     ("very loud", ["ff"]),
     ("very quiet", ["pp"]),
     ("very strong", ["ff"]),
     ("vessel", ["tin","can"]),
     ("vestment", ["alb"]),
     ("vicar", ["rev"]),
     ("victory", ["vj","v","ve"]),
     ("vide", ["v"]),
     ("violin string", ["a","e","g","d"]),
     ("violin strings", ["g","e"]),
     ("Virginia", ["va"]),
     ("viscount", ["vis"]),
     ("vitamin", ["h","k","bi","f","p","b","a","l","c","m","d","e","x"]),
     ("viz", ["sc"]),
     ("volt", ["v"]),
     ("volume", ["v","vol"]),
     ("volunteers", ["ta"]),
     ("vote", ["x"]),
     ("wall", ["mur"]),
     ("wander", ["err"]),
     ("warning", ["fore","cave"]),
     ("warrant officer", ["rsm"]),
     ("warship", ["sub"]),
     ("Washington", ["dc"]),
     ("water", ["ea","aq"]),
     ("waterfall", ["rain"]),
     ("watt", ["w"]),
     ("way", ["rly","ry","rd","st","ave"]),
     ("way of working", ["mo"]),
     ("weak", ["w"]),
     ("wearing", ["in"]),
     ("Wednesday", ["w"]),
     ("week", ["w"]),
     ("weight", ["g","oz","ton","gr","st","ct","wt","tonne"]),
     ("well", ["so"]),
     ("Welsh", ["w"]),
     ("Welsh riots", ["rebecca"]),
     ("west", ["w"]),
     ("West Indies", ["wi"]),
     ("western", ["w"]),
     ("Westminster", ["wi"]),
     ("whales", ["gam"]),
     ("what", ["que"]),
     ("when", ["as"]),
     ("who", ["qui"]),
     ("whole numbers", ["w"]),
     ("why", ["y"]),
     ("wicked sister", ["regan"]),
     ("wicket", ["w"]),
     ("width", ["w"]),
     ("wife", ["ux","rib","dutch","w"]),
     ("will", ["ill","to"]),
     ("William", ["w"]),
     ("win", ["v"]),
     ("wine", ["asti","port","tent"]),
     ("wings", ["ala"]),
     ("winner", ["ace"]),
     ("wise", ["ys","yy"]),
     ("witchcraft", ["obi"]),
     ("with", ["con"]),
     ("with a tenant", ["let"]),
     ("without", ["sin","sine"]),
     ("without a day fixed", ["sd"]),
     ("without children", ["sp"]),
     ("without date", ["sa"]),
     ("wizard place", ["oz"]),
     ("woman", ["f","her","w","eve","she"]),
     ("word processor", ["ear"]),
     ("work", ["opus","go","do","op"]),
     ("worker", ["ant","man","hand","bee"]),
     ("wreath", ["lei"]),
     ("writer", ["pen","elia","nib"]),
     ("writing", ["r","ms"]),
     ("wrong", ["sin"]),
     ("wrong sign", ["x"]),
     ("xi", ["x"]),
     ("Xmas", ["x"]),
     ("yard", ["y"]),
     ("year", ["a","y","yr"]),
     ("year of reign", ["ar"]),
     ("yearly meeting", ["agm"]),
     ("yellow", ["or"]),
     ("yen", ["y"]),
     ("yes", ["ja","oui","si","da","ay","aye"]),
     ("yew", ["u"]),
     ("yews", ["uu","us"]),
     ("you", ["u","ye"]),
     ("you and I", ["we"]),
     ("you and me", ["us"]),
     ("you are", ["ur"]),
     ("you queue", ["uq"]),
     ("you see", ["uc"]),
     ("you will, say", ["yule"]),
     ("young", ["y"]),
     ("young feller", ["washington"]),
     ("young sheep", ["teg"]),
     ("your", ["yr"]),
     ("yours truly", ["i"]),
     ("youth leaders", ["ys","wise"]),
     ("yttrium", ["y"]),
     ("Zaire", ["zr"]),
     ("Zambia", ["z"]),
     ("zed", ["z"]),
     ("zee", ["z"]),
     ("zero", ["z"]),
     ("zeta", ["z"])]
